name: kmap_test
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.83=py311h05b510d_0
  - blas=1.0=openblas
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py311h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.3.11=hca03da5_0
  - certifi=2024.6.2=py311hca03da5_0
  - cffi=1.16.0=py311h80987f9_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311hca03da5_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - cryptography=42.0.5=py311hd4332d6_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - fonttools=4.51.0=py311h80987f9_0
  - freetype=2.12.1=hadb7bae_2
  - idna=3.7=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - kiwisolver=1.4.4=py311h313beb8_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.12=he4db4b2_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.43=h091b4b1_0
  - libsqlite=3.45.2=h091b4b1_0
  - libtiff=4.4.0=hcbbed22_1
  - libwebp-base=1.3.2=h80987f9_0
  - libxcb=1.13=h9b22ae9_1004
  - libzlib=1.3.1=hfb2fe0b_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - logomaker=0.8=pyh864c0ab_1
  - lz4-c=1.9.4=h313beb8_1
  - matplotlib=3.8.0=py311hca03da5_0
  - matplotlib-base=3.8.0=py311h7aedaa7_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.3=pyhd8ed1ab_1
  - numexpr=2.8.7=py311h6dc990b_0
  - numpy=1.26.0=py311he598dae_0
  - numpy-base=1.26.0=py311hfbfe69c_0
  - openjpeg=2.5.0=h5d4e404_1
  - openssl=3.0.14=h80987f9_0
  - packaging=23.2=py311hca03da5_0
  - pandas=2.1.1=py311h7aedaa7_0
  - pillow=9.2.0=py311h09de4a2_3
  - pip=24.0=py311hca03da5_0
  - pthread-stubs=0.3=h1a28f6b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=24.0.0=py311hca03da5_0
  - pyparsing=3.0.9=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.0=h3ba56d0_1_cpython
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=py311hca03da5_0
  - readline=8.2=h1a28f6b_0
  - requests=2.31.0=py311hca03da5_0
  - scipy=1.11.3=py311hc76d9b0_0
  - setuptools=69.5.1=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.2=hf2abe2d_0
  - tk=8.6.13=h5083fa2_1
  - tomli-w=1.0.0=pyhd3eb1b0_0
  - tornado=6.4.1=py311h80987f9_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h80987f9_0
  - urllib3=1.26.19=py311hca03da5_0
  - wheel=0.43.0=py311hca03da5_0
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.3.1=hfb2fe0b_1
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - colorama==0.4.6
      - dill==0.3.8
      - kmer-map==0.0.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - pygments==2.18.0
      - rich==13.7.1
      - taichi==1.7.1
